pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    terraform init
                    terraform plan
                    terraform apply
                '''
            }
        }
    }
}
