pipeline {
    agent { label 'jenkins_vinay'}
    stages {
        stage('Build') {
            steps {
                sh '''
                    terraform init
                    terraform plan
                    terraform apply
                '''
            }
        }
    }
}
