pipeline {
    agent { label 'jenkins_vinay'}
    stages {
        stage('Build') {
            steps {
                sh '''
                    git clone https://github.com/saivinay98/terraform-task.git
                    cd terraform-task
                    terraform init
                    terraform plan
                    terraform apply --auto-approve
                '''
            }
        }
    }
}
